### ISSUE TITLE
Receiving access token

### ISSUE THREAD

**Issue by ydusaniuk** [DukeNuken/Duke.Owin.VkontakteMiddleware#11]
Where i can get access token in code after login for working with VK API?

**Comment by DukeNuken** [comment]
https://vk.com/dev/access_token?f=1.%20%D0%9A%D0%BB%D1%8E%D1%87%20%D0%B4%D0%BE%D1%81%D1%82%D1%83%D0%BF%D0%B0%20%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D1%8F
