### ISSUE TITLE
can not log in via VK

### ISSUE THREAD

**Issue by vailukhin** [DukeNuken/Duke.Owin.VkontakteMiddleware#13]
Good afternoon! When authorizing through the VC - there is no authorization. An authorization form appears, I enter the data. After that, I return to my site in an unauthorized state.

I tried to go to the site, which you posted as an example of the authorization work (freelistenonline.com) - not it all happens just like mine.

**Comment by alexus1024** [comment]
yes, it seems to vk turned off some legacy API support
Some chanes should be done to fix it.

This issue has been fixed in another project recetly:
https://github.com/TerribleDev/OwinOAuthProviders/pull/228/files

**Comment by DukeNuken** [comment]
fixed
