### ISSUE TITLE
Full-sized profile picture

### ISSUE THREAD

**Issue by siberianguy** [DukeNuken/Duke.Owin.VkontakteMiddleware#6]
Thanks for you work! Great job! I've integrated your authentication provider to my web site and everything works fine. The only minor issue I have is that I need to get a full-sized user profile picture but the only picture I found was a small thumbnail. Here is the code I used:

```
            var vkAuthenticationOptions = new VkAuthenticationOptions()
            {
                AppId = "...",
                AppSecret = "...",
                Scope = "email,photos",
                Provider = new VkAuthenticationProvider()
                {
                    OnAuthenticated = context =>
                    {
                        context.Identity.AddClaim(new Claim("picture", context.Link));

                        return Task.FromResult(0);
                    }
                }
            };
            app.UseVkontakteAuthentication(vkAuthenticationOptions);
```

context.Link stores that thumbnail I mentioned above. I tried to add "photos" scope but it doesn't look like something has changed. Should I somehow request that photos manually?

**Comment by DukeNuken** [comment]
you should use vk api for get info like that
